"use client";

import { ArrowLeft, ArrowRight, BadgeCheck } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import type { TestimonialSummary } from "@/features/testimonials/types";

export function TestimonialsCarousel({ testimonials, eyebrow, title }: { testimonials: TestimonialSummary[]; eyebrow: string; title: string }) {
  const [index, setIndex] = useState(0);
  const touchStart = useRef<number | null>(null);
  const average = useMemo(() => testimonials.length ? (testimonials.reduce((sum, item) => sum + item.rating, 0) / testimonials.length).toFixed(1) : "", [testimonials]);
  if (!testimonials.length) return null;
  const visible = Array.from({ length: Math.min(3, testimonials.length) }, (_, offset) => testimonials[(index + offset) % testimonials.length]);
  const move = (direction: number) => setIndex((current) => (current + direction + testimonials.length) % testimonials.length);
  return <section className="bg-[#f4faff] px-5 py-[66px] sm:px-8 lg:px-12 xl:px-[112px]" aria-labelledby="testimonials-title" onKeyDown={(event) => { if (event.key === "ArrowLeft") move(-1); if (event.key === "ArrowRight") move(1); }} onTouchStart={(event) => { touchStart.current = event.touches[0]?.clientX ?? null; }} onTouchEnd={(event) => { if (touchStart.current === null) return; const distance = (event.changedTouches[0]?.clientX ?? touchStart.current) - touchStart.current; if (Math.abs(distance) > 45) move(distance > 0 ? -1 : 1); touchStart.current = null; }} tabIndex={0}>
    <div className="mx-auto max-w-[1313px]"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-[700px]"><p className="text-[13px] font-black uppercase leading-[13px] tracking-[0.08em] text-leehov-blue-500">{eyebrow}</p><h2 id="testimonials-title" className="mt-[18px] text-[40px] font-extrabold leading-[46px] text-[#153b5b] sm:text-[42px] sm:leading-[50px]">{title}</h2><p className="mt-[18px] text-[15px] leading-6 text-[#6d879d]">Histórias reais de viajantes que viveram experiências acompanhadas pela Leehov.</p></div>{average ? <div className="flex items-center gap-3 rounded-full border border-[#d7e7f5] bg-white px-4 py-3 text-sm font-bold text-[#153b5b]"><span className="text-amber-400">★</span>{average} de 5 · {testimonials.length} {testimonials.length === 1 ? "avaliação" : "avaliações"}</div> : null}</div>
      <div className="mt-12 grid gap-[30px] md:grid-cols-3">{visible.map((testimonial, offset) => <article key={`${testimonial.id}-${offset}`} className={`${offset ? "hidden md:flex" : "flex"} min-h-[240px] flex-col rounded-[14px] border border-[#d7e7f5] bg-white p-7 shadow-[0_10px_28px_rgb(13_54_83_/_6%)]`}><div className="flex items-start justify-between gap-4"><span className="text-sm tracking-[0.12em] text-amber-400" aria-label={`${testimonial.rating} de 5 estrelas`}>{"★".repeat(testimonial.rating)}</span>{testimonial.source === "google" ? <span className="flex items-center gap-1 text-[11px] font-bold text-leehov-blue-600"><BadgeCheck className="size-4" />Google</span> : null}</div><blockquote className="mt-5 flex-1 text-[15px] leading-[25px] text-[#41627d]">“{testimonial.text}”</blockquote><div className="mt-6 flex items-center gap-3">{testimonial.imageUrl ? <div className="size-10 rounded-full bg-cover bg-center" style={{ backgroundImage: `url(${testimonial.imageUrl})` }} role="img" aria-label={testimonial.name} /> : <div className="flex size-10 items-center justify-center rounded-full bg-[#e4f4ff] font-black text-leehov-blue-600">{testimonial.name.slice(0, 1).toUpperCase()}</div>}<div><p className="font-extrabold text-[#153b5b]">{testimonial.name}</p><p className="text-xs text-[#7891a8]">{[testimonial.roleTitle, testimonial.city].filter(Boolean).join(" · ")}</p></div></div></article>)}</div>
      {testimonials.length > 1 ? <div className="mt-9 flex items-center justify-between"><div className="flex gap-2" aria-label="Posição no carrossel">{testimonials.map((item, itemIndex) => <button key={item.id} type="button" onClick={() => setIndex(itemIndex)} className={`rounded-full transition-all ${itemIndex === index ? "h-2 w-7 bg-leehov-blue-500" : "size-2 bg-[#c9ddea]"}`} aria-label={`Ver depoimento ${itemIndex + 1}`} aria-current={itemIndex === index} />)}</div><div className="flex gap-3"><Button variant="outline" size="icon-lg" className="size-12 rounded-full border-[#d7e7f5] bg-white" onClick={() => move(-1)} aria-label="Depoimentos anteriores"><ArrowLeft /></Button><Button variant="outline" size="icon-lg" className="size-12 rounded-full border-[#d7e7f5] bg-white" onClick={() => move(1)} aria-label="Próximos depoimentos"><ArrowRight /></Button></div></div> : null}
    </div>
  </section>;
}
